### ISSUE TITLE
Install ejs and express with --save

### ISSUE THREAD

**Issue by chaseadamsio** [joberst/blog#2]
When installing node dependencies, if they're going to be used as part of the environment, it's best to run the following at the root of your project (with express as an example):
```
npm install express --save
```
This will 1) install the module into your `node_modules` directory and and add the dependency to your `package.json`.

This is best practice for a few reasons:

- If you're going to run this on a server, there should be a "hook", either one you set up or set up by your hosting provider that runs `npm install` and installs the dependencies before starting up your application. If there are no dependencies, the server will fail to start since express doesn't exist.
- If you work with other people, when they pull down your project and run `npm install`, this will install all the dependencies at the minor version specified at once so they don't have to do it individually by going through files and figuring out which dependencies you have.

**Comment by joberst** [comment]
Is this correct?
![image](https://cloud.githubusercontent.com/assets/3642777/7641930/d6805c84-fa41-11e4-847f-f176e9c74502.png)
