### ISSUE TITLE
Relative paths are incorrect for includes in default.ejs

### ISSUE THREAD

**Issue by chaseadamsio** [joberst/blog#3]
The includes in the project are relative to where the file calling them lives.

For instance, if you have default.ejs in `views` all includes should be relative to `views`, so in the case that you want a file in partials, you'd have: 

```
  <% include partials/page/header.ejs %>
```

**Comment by joberst** [comment]
thanks! removed 'views'

**Comment by joberst** [comment]
ah, was just about to commit w/ the Fix msg :)
